name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  provider: ^6.1.2
  lottie: ^2.5.0
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  shared_preferences: ^2.5.3
  jwt_decoder: ^2.0.1
  flip_card: ^0.7.0
  url_launcher: ^6.0.10




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/animations/cyber_welcome.json

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji-Regular.ttf
